### ISSUE TITLE
Whole website broken, when logged in

### ISSUE THREAD

**Issue by BulletsBreath** [slotlist/slotlist-backend#113]
As long as i'm not logged in on slotlist, the mission calendar loads up fine, i can acces missions, look at the communities page and so on.

At the moment i'm logged in, the whole site is broken. No page is able to load anymore. This happens with different browsers, different devices (desktop PC, several mobile phones, tablet). 

The error messages i get are for example:

 Laden der Missionen ist fehlgeschlagen - Request fehlgeschlagen
 Laden der Anzahl an ungelesenen Benachrichtigungen ist fehlgeschlagen - Request fehlgeschlagen
 Laden der Missionen für den Kalender ist fehlgeschlagen - Request fehlgeschlagen

This not only happens for me, but for other players in my community as well. It started with the last update.

![slotlisterror](https://user-images.githubusercontent.com/86913610/129476326-b506341e-b0ed-4732-8df1-97ae7c1b4587.JPG)

**Comment by MorpheusXAUT** [comment]
Hi,

could you provide me with some names of users this problem occurs or the name of your community? At a first glance, I don't see any errors in the recent backend logs.
If you can, the output of the browser console (by default `CTRL + SHIFT + I` on Windows for Chrome and Firefox, I believe) and the time the issue happened would be helpful in trying to debug as well.

**Comment by BulletsBreath** [comment]
Hi, 

ofc:

The community is TacNet / Tactical Network

Users for example NSCT (me) or Max.
Feel free to contact me by steam by the mentioned name if you need any more info or a debugging via Teamviewer or else.

Im just gonna try again right now, 17:21 at 2021/08/15. 
Is there a way to save the output you need to a file, as it seems to be quite much? Oh and btw. i of course disabled adblock and Noscript for slotlist when the problems occured.

**Comment by MorpheusXAUT** [comment]
Hi,

sorry for the delay.
You should be able to save the console log in Chrome via right-click in the console -> `Save as...` and right-click on the message -> `Export visible messages to File` in Firefox.

Depending on the logs, a debug session might be useful to help find the issue, unfortunately I won't find time for that until Sunday earliest.

**Comment by BulletsBreath** [comment]
Hi,
no problem. As stated above, feel free to contact me at steam by the name NSCT if you need a debugging session. 

The requested log:
[console-export-2021-8-19_22-14-44.txt](https://github.com/slotlist/slotlist-backend/files/7017479/console-export-2021-8-19_22-14-44.txt)

**Comment by MorpheusXAUT** [comment]
Thanks for the log. Seems like a CORS header is supposed to be missing, although it's definitely there for me...
I've changed the header from a stricter setting to always returning a wildcard, although I'd be surprised if that changes anything.

What makes even less sense is this breaking after you log in, it should either be completely broken, or not at all, but worth a shot anyways - could you try again?

What browser/version are you using btw?

**Comment by BulletsBreath** [comment]
Tried it again, unfortunately it didnt work.

Im using Firefox 91.0.1, i tried it in Edge  92.0.902.78 also and on 2 Smartphones and a Tablet as well. I can find out their browser versions as well if you need me to. No Adblock, Noscript or other addons installed on the smartphones, the tablet or for edge btw.

**Comment by MorpheusXAUT** [comment]
I'll close this issue for now as the latest changes (to be pushed to GitHub shortly) seem to have resolved the issue.
Thanks for the report and help with troubleshooting and testing!
